#!/usr/bin/env python3
"""
Script placeholder for Jupyter notebooks.
Run this script to generate the .ipynb notebook files programmatically.

Usage:
    python notebooks/generate_notebooks.py
"""

import json
from pathlib import Path


def make_notebook(cells: list) -> dict:
    """Create a Jupyter notebook dict from a list of (type, source) tuples."""
    notebook_cells = []
    for cell_type, source in cells:
        if cell_type == "markdown":
            cell = {
                "cell_type": "markdown",
                "metadata": {},
                "source": source if isinstance(source, list) else [source]
            }
        else:
            cell = {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source if isinstance(source, list) else [source]
            }
        notebook_cells.append(cell)

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": notebook_cells
    }


# ─────────────────────────────────────────────────────────────────────────────
# Notebook 1: Dataset Exploration
# ─────────────────────────────────────────────────────────────────────────────
nb1_cells = [
    ("markdown", [
        "# 📊 01 — Dataset Exploration\n",
        "**Tujuan:** Eksplorasi dataset Kaggle RFT (River Floating Trash) sebelum training.\n\n",
        "Notebook ini mencakup:\n",
        "1. Verifikasi dataset Kaggle RFT (8 kelas)\n",
        "2. Analisis distribusi kelas\n",
        "3. Analisis ukuran objek (untuk menentukan threshold 'objek kecil')\n",
        "4. Visualisasi contoh anotasi\n",
        "5. Ringkasan struktur YOLO dataset\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')  # Add project root to path\n",
        "\n",
        "import json\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.patches as mpatches\n",
        "from pathlib import Path\n",
        "from collections import Counter\n",
        "import cv2\n",
        "from PIL import Image\n",
        "\n",
        "# Project config\n",
        "import yaml\n",
        "with open('../config/config.yaml') as f:\n",
        "    cfg = yaml.safe_load(f)\n",
        "\n",
        "print('✅ Config loaded')\n",
        "print(f'Project: {cfg[\"project\"][\"name\"]}')\n",
        "print(f'Classes: {cfg[\"dataset\"][\"class_names\"]}')\n"
    ]),
    ("markdown", "## Step 1: Verifikasi Dataset Kaggle RFT"),
    ("code", [
        "import subprocess\n",
        "import os\n",
        "\n",
        "os.makedirs('../logs', exist_ok=True)\n",
        "os.makedirs('../results/visualizations', exist_ok=True)\n",
        "\n",
        "# Verifikasi dataset yang sudah ada\n",
        "from pathlib import Path\n",
        "dataset_dir = Path('../data/datasets')\n",
        "print(f'Dataset dir exists: {dataset_dir.exists()}')\n",
        "for split in ['train', 'valid', 'test']:\n",
        "    n_imgs = len(list((dataset_dir / split / 'images').glob('*'))) if (dataset_dir / split / 'images').exists() else 0\n",
        "    n_lbls = len(list((dataset_dir / split / 'labels').glob('*.txt'))) if (dataset_dir / split / 'labels').exists() else 0\n",
        "    print(f'  {split:6s}: {n_imgs} images, {n_lbls} labels')\n"
    ]),
    ("markdown", "## Step 2: Load and Analyze Annotations"),
    ("code", [
        "ann_path = Path('../data/raw/annotations.json')\n",
        "\n",
        "if not ann_path.exists():\n",
        "    print('⚠️  Annotations not found. Run download first.')\n",
        "else:\n",
        "    with open(ann_path) as f:\n",
        "        taco_data = json.load(f)\n",
        "    \n",
        "    print(f'📊 TACO Dataset Statistics:')\n",
        "    print(f'   Images     : {len(taco_data[\"images\"])}')\n",
        "    print(f'   Annotations: {len(taco_data[\"annotations\"])}')\n",
        "    print(f'   Categories : {len(taco_data[\"categories\"])}')\n",
        "    print()\n",
        "    print('Categories:')\n",
        "    for cat in taco_data['categories'][:15]:\n",
        "        print(f'   [{cat[\"id\"]:3d}] {cat[\"name\"]}')\n"
    ]),
    ("markdown", "## Step 2: Analisis Distribusi Kelas"),
    ("code", [
        "# Kelas dataset Kaggle RFT (8 kelas)\n",
        "CLASS_NAMES = ['bottle', 'grass', 'branch', 'milk-box', 'plastic-bag', 'plastic-garbage', 'ball', 'leaf']\n",
        "CLASS_COLORS = ['#ff8000', '#00c864', '#8b5a2b', '#0078ff', '#dc0096', '#8c00ff', '#00dcdc', '#b4c83c']\n",
        "\n",
        "# Hitung distribusi label dari dataset\n",
        "from collections import Counter\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from pathlib import Path\n",
        "\n",
        "class_counts = Counter()\n",
        "for split in ['train', 'valid', 'test']:\n",
        "    lbl_dir = Path('../data/datasets') / split / 'labels'\n",
        "    if lbl_dir.exists():\n",
        "        for lbl_file in lbl_dir.glob('*.txt'):\n",
        "            for line in lbl_file.read_text().strip().splitlines():\n",
        "                parts = line.split()\n",
        "                if parts:\n",
        "                    class_counts[int(parts[0])] += 1\n",
        "\n",
        "print('📊 Distribusi Kelas Kaggle RFT:')\n",
        "print(f'{\"Kelas\":<20} {\"Jumlah\":<10} {\"Persen\"}')\n",
        "print('-' * 40)\n",
        "total = sum(class_counts.values())\n",
        "for cls_id, name in enumerate(CLASS_NAMES):\n",
        "    count = class_counts.get(cls_id, 0)\n",
        "    print(f'{name:<20} {count:<10} {count/total*100:.1f}%')\n",
        "print(f'{\"TOTAL\":<20} {total}')\n"
    ]),
    ("code", [
        "# Plot distribusi kelas\n",
        "names = CLASS_NAMES\n",
        "counts = [class_counts.get(i, 0) for i in range(len(CLASS_NAMES))]\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(12, 5))\n",
        "bars = ax.barh(names[::-1], counts[::-1], color=CLASS_COLORS[::-1])\n",
        "ax.set_title('Kaggle RFT Dataset — Distribusi Kelas (8 Kelas)', fontsize=14, fontweight='bold')\n",
        "ax.set_xlabel('Jumlah Anotasi')\n",
        "for bar, count in zip(bars, counts[::-1]):\n",
        "    ax.text(bar.get_width() + 1, bar.get_y() + bar.get_height()/2,\n",
        "            str(count), va='center')\n",
        "plt.tight_layout()\n",
        "plt.savefig('../results/visualizations/class_distribution_rft.png', dpi=150)\n",
        "plt.show()\n"
    ]),
    ("markdown", "## Step 3: Analisis Ukuran Objek"),
    ("code", [
        "# Analisis ukuran bounding box dari dataset\n",
        "areas = []\n",
        "for split in ['train', 'valid', 'test']:\n",
        "    lbl_dir = Path('../data/datasets') / split / 'labels'\n",
        "    img_dir = Path('../data/datasets') / split / 'images'\n",
        "    if not lbl_dir.exists(): continue\n",
        "    for lbl_file in lbl_dir.glob('*.txt'):\n",
        "        img_files = list(img_dir.glob(lbl_file.stem + '.*'))\n",
        "        if not img_files: continue\n",
        "        import cv2\n",
        "        img = cv2.imread(str(img_files[0]))\n",
        "        if img is None: continue\n",
        "        H, W = img.shape[:2]\n",
        "        for line in lbl_file.read_text().strip().splitlines():\n",
        "            parts = line.split()\n",
        "            if len(parts) == 5:\n",
        "                _, xc, yc, w, h = int(parts[0]), *map(float, parts[1:])\n",
        "                areas.append(w * W * h * H)\n",
        "\n",
        "areas = np.array(areas)\n",
        "small_mask  = areas < 1024\n",
        "medium_mask = (areas >= 1024) & (areas < 9216)\n",
        "large_mask  = areas >= 9216\n",
        "\n",
        "print('📐 Distribusi Ukuran Objek:')\n",
        "print(f'   Total anotasi : {len(areas)}')\n",
        "print(f'   Small  (<32×32): {small_mask.sum()} ({small_mask.mean()*100:.1f}%)')\n",
        "print(f'   Medium (32-96) : {medium_mask.sum()} ({medium_mask.mean()*100:.1f}%)')\n",
        "print(f'   Large  (>96×96): {large_mask.sum()} ({large_mask.mean()*100:.1f}%)')\n",
        "print(f'   Median area    : {np.median(areas):.0f} px²')\n"
    ]),
    ("markdown", "## Step 4: Verifikasi Struktur YOLO Dataset"),
    ("code", [
        "# Verifikasi data.yaml jika ada\n",
        "import yaml\n",
        "data_yaml_path = Path('../data/datasets/data.yaml')\n",
        "if data_yaml_path.exists():\n",
        "    with open(data_yaml_path) as f:\n",
        "        data_cfg = yaml.safe_load(f)\n",
        "    print('data.yaml:')\n",
        "    print(f'  Classes: {data_cfg.get(\"nc\", \"?\")}')\n",
        "    print(f'  Names  : {data_cfg.get(\"names\", [])}')\n",
        "else:\n",
        "    print('data.yaml tidak ditemukan — menggunakan kelas default:')\n",
        "    print(f'  8 kelas: {CLASS_NAMES}')\n"
    ]),
    ("markdown", "## Step 5: Visualisasi Sample Gambar"),
    ("code", [
        "# Visualize a few training samples with annotations\n",
        "import cv2\n",
        "\n",
        "train_img_dir = Path('../data/datasets/train/images')\n",
        "train_lbl_dir = Path('../data/datasets/train/labels')\n",
        "\n",
        "sample_images = list(train_img_dir.glob('*'))[:6]\n",
        "class_names = CLASS_NAMES\n",
        "\n",
        "if sample_images:\n",
        "    fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n",
        "    \n",
        "    for ax, img_path in zip(axes.flatten(), sample_images):\n",
        "        img = cv2.imread(str(img_path))\n",
        "        if img is None: continue\n",
        "        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
        "        H, W = img.shape[:2]\n",
        "        \n",
        "        lbl_path = train_lbl_dir / (img_path.stem + '.txt')\n",
        "        if lbl_path.exists():\n",
        "            for line in lbl_path.read_text().strip().splitlines():\n",
        "                parts = line.split()\n",
        "                if len(parts) == 5:\n",
        "                    c, xc, yc, w, h = int(parts[0]), *map(float, parts[1:])\n",
        "                    x1 = int((xc - w/2) * W); y1 = int((yc - h/2) * H)\n",
        "                    x2 = int((xc + w/2) * W); y2 = int((yc + h/2) * H)\n",
        "                    cv2.rectangle(img_rgb, (x1,y1), (x2,y2), (255,100,0), 2)\n",
        "                    cv2.putText(img_rgb, class_names[c], (x1, y1-5),\n",
        "                                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,100,0), 1)\n",
        "        \n",
        "        ax.imshow(img_rgb)\n",
        "        ax.set_title(img_path.stem[:25], fontsize=9)\n",
        "        ax.axis('off')\n",
        "    \n",
        "    plt.suptitle('Sample Training Images — Kaggle RFT Dataset', fontsize=14, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sample_annotations_rft.png', dpi=150)\n",
        "    plt.show()\n",
        "else:\n",
        "    print('No training images found.')\n"
    ]),
    ("markdown", "---\n\n✅ **Dataset exploration complete!**\n\nNext step: Buka `02_training.ipynb` untuk melihat konfigurasi training dan validasi model yang sudah ada.")
]

# ─────────────────────────────────────────────────────────────────────────────
# Notebook 2: Training
# ─────────────────────────────────────────────────────────────────────────────
nb2_cells = [
    ("markdown", [
        "# 🚀 02 — Training YOLOv11n\n",
        "**Tujuan:** Training YOLOv11n pada dataset Kaggle RFT (8 kelas sampah sungai).\n\n",
        "> ✅ **Status:** Training 100 epoch sudah selesai. `weights/best.pt` sudah tersedia.\n",
        "> Notebook ini untuk keperluan dokumentasi dan jika ingin melakukan training ulang.\n",
        ">\n",
        "> ⚠️ Training dari awal membutuhkan beberapa jam. Disarankan menggunakan GPU.\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')\n",
        "\n",
        "import os\n",
        "from pathlib import Path\n",
        "import yaml\n",
        "import torch\n",
        "\n",
        "print(f'PyTorch version: {torch.__version__}')\n",
        "print(f'CUDA available : {torch.cuda.is_available()}')\n",
        "print(f'MPS available  : {torch.backends.mps.is_available()}')\n",
        "\n",
        "# Check ultralytics\n",
        "try:\n",
        "    import ultralytics\n",
        "    print(f'Ultralytics    : {ultralytics.__version__}')\n",
        "except ImportError:\n",
        "    print('❌ ultralytics not installed — pip install ultralytics')\n"
    ]),
    ("markdown", "## Step 1: Cek Model yang Sudah Ada"),
    ("code", [
        "from pathlib import Path\n",
        "from ultralytics import YOLO\n",
        "import torch\n",
        "\n",
        "weights_path = Path('../weights/best.pt')\n",
        "print(f'Model tersedia: {weights_path.exists()}')\n",
        "print(f'Ukuran file  : {weights_path.stat().st_size / 1024 / 1024:.2f} MB' if weights_path.exists() else '')\n",
        "\n",
        "if weights_path.exists():\n",
        "    model = YOLO(str(weights_path))\n",
        "    print(f'✅ Model berhasil dimuat!')\n",
        "    print(f'   Device: CPU')\n",
        "    print(f'   Dataset: Kaggle RFT (8 kelas)')\n",
        "    print(f'   Training: 100 epoch')\n",
        "else:\n",
        "    print('⚠️  weights/best.pt tidak ditemukan — lanjutkan ke training baru di bawah')\n"
    ]),
    ("markdown", "## Step 2: Cek Dataset"),
    ("code", [
        "dataset_dir = Path('../data/datasets')\n",
        "print(f'Dataset dir: {dataset_dir}')\n",
        "print(f'Exists     : {dataset_dir.exists()}')\n",
        "\n",
        "for split in ['train', 'valid', 'test']:\n",
        "    n = len(list((dataset_dir / split / 'images').glob('*'))) if (dataset_dir / split / 'images').exists() else 0\n",
        "    print(f'  {split:6s}: {n} images')\n"
    ]),
    ("markdown", "## Step 2: Load Model"),
    ("code", [
        "from ultralytics import YOLO\n",
        "\n",
        "# Try YOLOv11n first, fallback to YOLOv8n\n",
        "model_candidates = ['yolo11n.pt', 'yolov8n.pt']\n",
        "model = None\n",
        "model_name_used = None\n",
        "\n",
        "for candidate in model_candidates:\n",
        "    try:\n",
        "        model = YOLO(candidate)\n",
        "        model_name_used = candidate\n",
        "        print(f'✅ Loaded: {candidate}')\n",
        "        break\n",
        "    except Exception as e:\n",
        "        print(f'⚠️  {candidate}: {e}')\n",
        "\n",
        "if model is None:\n",
        "    raise RuntimeError('Could not load any YOLO model')\n",
        "\n",
        "# Model info\n",
        "print(f'\\nModel: {model_name_used}')\n",
        "print(f'Parameters: {sum(p.numel() for p in model.model.parameters()):,}')\n"
    ]),
    ("markdown", "## Step 3: Konfigurasi Training Ulang (Opsional)"),
    ("code", [
        "# Konfigurasi training yang SUDAH DIGUNAKAN\n",
        "# (Jalankan ini hanya jika ingin training ulang dari awal)\n",
        "TRAIN_CONFIG = {\n",
        "    'data': '../data/datasets/data.yaml',  # Dataset Kaggle RFT\n",
        "    'epochs': 100,\n",
        "    'imgsz': 640,\n",
        "    'batch': 8,\n",
        "    'device': '0' if torch.cuda.is_available() else 'cpu',\n",
        "    'project': 'C:/yolo_out',\n",
        "    'name': 'rft_run',\n",
        "    'patience': 20,\n",
        "    'lr0': 0.01,\n",
        "    'lrf': 0.001,\n",
        "    'cos_lr': True,\n",
        "    'amp': False,\n",
        "    'save': True,\n",
        "}\n",
        "\n",
        "print('Konfigurasi training:')\n",
        "for k, v in TRAIN_CONFIG.items():\n",
        "    print(f'  {k}: {v}')\n"
    ]),
    ("markdown", "## Step 4: Jalankan Quick Validation"),
    ("code", [
        "# Validasi model yang sudah ada pada test set\n",
        "best_model = YOLO('../weights/best.pt')\n",
        "\n",
        "import yaml\n",
        "data_yaml_path = Path('../data/datasets/data.yaml')\n",
        "\n",
        "val_results = best_model.val(\n",
        "    data=str(data_yaml_path.resolve()) if data_yaml_path.exists() else None,\n",
        "    split='test',\n",
        "    imgsz=640,\n",
        "    conf=0.15,\n",
        "    iou=0.5,\n",
        "    device='cpu',\n",
        "    verbose=True\n",
        ")\n",
        "\n",
        "print('\\n📊 Test Set Results:')\n",
        "print(f'  mAP@0.5     : {val_results.box.map50:.4f}')\n",
        "print(f'  mAP@0.5:0.95: {val_results.box.map:.4f}')\n",
        "print(f'  Precision   : {val_results.box.mp:.4f}')\n",
        "print(f'  Recall      : {val_results.box.mr:.4f}')\n"
    ]),
    ("markdown", "## Step 5: Plot Training Curves"),
    ("code", [
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.image as mpimg\n",
        "from pathlib import Path\n",
        "\n",
        "# Cek hasil training curves dari Ultralytics\n",
        "run_dir = Path('C:/yolo_out/rft_run')\n",
        "results_csv = run_dir / 'results.csv'\n",
        "\n",
        "if results_csv.exists():\n",
        "    import pandas as pd\n",
        "    df = pd.read_csv(results_csv)\n",
        "    df.columns = df.columns.str.strip()\n",
        "    \n",
        "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "    epochs = df.index + 1\n",
        "    if 'metrics/mAP50(B)' in df.columns:\n",
        "        axes[0].plot(epochs, df['metrics/mAP50(B)'], label='mAP@0.5', color='blue')\n",
        "    if 'metrics/mAP50-95(B)' in df.columns:\n",
        "        axes[0].plot(epochs, df['metrics/mAP50-95(B)'], label='mAP@0.5:0.95', color='orange')\n",
        "    axes[0].set_title(f'Training Progress — YOLOv11n on Kaggle RFT')\n",
        "    axes[0].set_xlabel('Epoch'); axes[0].legend()\n",
        "    if 'train/box_loss' in df.columns:\n",
        "        axes[1].plot(epochs, df['train/box_loss'], label='Box Loss', color='red')\n",
        "    axes[1].set_title('Training Loss'); axes[1].set_xlabel('Epoch'); axes[1].legend()\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/training_curves_rft.png', dpi=150)\n",
        "    plt.show()\n",
        "else:\n",
        "    print(f'results.csv tidak ditemukan di: {run_dir}')\n"
    ]),
    ("markdown", "---\n\n✅ **Training complete!**\n\nNext step: Run `03_inference_evaluation.ipynb` for SAHI inference benchmark and comparison.")
]


# ─────────────────────────────────────────────────────────────────────────────
# Notebook 3: Inference & Evaluation
# ─────────────────────────────────────────────────────────────────────────────
nb3_cells = [
    ("markdown", [
        "# 🔍 03 — Inference & Evaluation\n",
        "**Tujuan:** Evaluasi komprehensif YOLO+SAHI vs YOLO saja pada test set.\n\n",
        "Notebook ini mencakup:\n",
        "1. Setup inferensi CPU-only (simulasi keterbatasan resource)\n",
        "2. SAHI inference vs full-image inference\n",
        "3. Benchmark latency dan FPS\n",
        "4. Evaluasi mAP@0.5 dan mAP@0.5:0.95\n",
        "5. Analisis objek kecil (small object recall)\n",
        "6. Visualisasi hasil deteksi\n",
        "7. Export laporan CSV\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')\n",
        "\n",
        "import os\n",
        "import cv2\n",
        "import numpy as np\n",
        "import torch\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from pathlib import Path\n",
        "import yaml\n",
        "\n",
        "print('Environment check:')\n",
        "print(f'  PyTorch     : {torch.__version__}')\n",
        "\n",
        "# Check SAHI\n",
        "try:\n",
        "    import sahi\n",
        "    print(f'  SAHI        : {sahi.__version__} ✅')\n",
        "    SAHI_AVAILABLE = True\n",
        "except ImportError:\n",
        "    print('  SAHI        : NOT AVAILABLE — using manual fallback')\n",
        "    SAHI_AVAILABLE = False\n",
        "\n",
        "MODEL_PATH = '../weights/best.pt'\n",
        "DATA_YAML  = '../data/datasets/data.yaml'\n",
        "CLASS_NAMES = ['bottle', 'grass', 'branch', 'milk-box', 'plastic-bag', 'plastic-garbage', 'ball', 'leaf']\n",
        "\n",
        "print(f'  Model       : {MODEL_PATH}')\n",
        "print(f'  Model exists: {Path(MODEL_PATH).exists()}')\n",
        "print(f'  Kelas       : {CLASS_NAMES}')\n"
    ]),
    ("markdown", "## Step 1: Setup CPU-only Inference"),
    ("code", [
        "from src.cpu_inference import setup_cpu_inference\n",
        "\n",
        "config = setup_cpu_inference(num_threads=4)\n",
        "print('CPU Inference config:', config)\n",
        "print(f'Threads: {config[\"num_threads\"]}')\n",
        "print(f'CUDA disabled: {config[\"cuda_disabled\"]}')\n",
    ]),
    ("markdown", "## Step 2: Load Predictors"),
    ("code", [
        "# Initialize SAHI predictor (or manual fallback)\n",
        "CONF = 0.25\n",
        "IOU  = 0.5\n",
        "SLICE_SIZE = 640\n",
        "OVERLAP = 0.2\n",
        "\n",
        "if SAHI_AVAILABLE:\n",
        "    from src.inference_sahi import SAHIPredictor\n",
        "    predictor = SAHIPredictor(\n",
        "        model_path=MODEL_PATH,\n",
        "        confidence_threshold=CONF,\n",
        "        iou_threshold=IOU,\n",
        "        slice_size=SLICE_SIZE,\n",
        "        overlap_ratio=OVERLAP,\n",
        "        device='cpu'\n",
        "    )\n",
        "    print('✅ SAHI predictor initialized')\n",
        "else:\n",
        "    from src.inference_manual import ManualSlicingPredictor\n",
        "    predictor = ManualSlicingPredictor(\n",
        "        model_path=MODEL_PATH,\n",
        "        slice_size=SLICE_SIZE,\n",
        "        overlap_ratio=OVERLAP,\n",
        "        confidence_threshold=CONF,\n",
        "        iou_threshold=IOU,\n",
        "        device='cpu'\n",
        "    )\n",
        "    print('✅ Manual slicing predictor initialized (SAHI fallback)')\n"
    ]),
    ("markdown", "## Step 3: Visualisasi Strategi SAHI Slicing"),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')\n",
        "from src.gui import generate_slices  # reuse same function\n",
        "\n",
        "test_img_dir = Path('../data/datasets/test/images')\n",
        "sample_imgs = list(test_img_dir.glob('*'))[:1]\n",
        "\n",
        "if sample_imgs:\n",
        "    sample_img = cv2.imread(str(sample_imgs[0]))\n",
        "    H, W = sample_img.shape[:2]\n",
        "    slices = generate_slices(H, W, 640, 0.2)\n",
        "    \n",
        "    # Visualize slices\n",
        "    vis = sample_img.copy()\n",
        "    for (x1,y1,x2,y2) in slices:\n",
        "        cv2.rectangle(vis, (x1,y1), (x2,y2), (0,200,100), 2)\n",
        "    vis_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)\n",
        "    \n",
        "    plt.figure(figsize=(12, 8))\n",
        "    plt.imshow(vis_rgb)\n",
        "    plt.title(f'SAHI Slicing: {len(slices)} patch pada {W}×{H} gambar', fontsize=13)\n",
        "    plt.axis('off')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sahi_slicing.png', dpi=150)\n",
        "    plt.show()\n",
        "    print(f'Jumlah patch: {len(slices)} (slice=640, overlap=0.2)')\n",
        "else:\n",
        "    print('Tidak ada gambar test ditemukan.')\n"
    ]),
    ("markdown", "## Step 4: SAHI vs Full-Image — Single Image Comparison"),
    ("code", [
        "from src.utils.visualization import draw_detections, draw_comparison\n",
        "\n",
        "if sample_imgs:\n",
        "    img = cv2.imread(str(sample_imgs[0]))\n",
        "    \n",
        "    print('Running SAHI sliced prediction...')\n",
        "    sahi_result = predictor.predict(img)\n",
        "    print(f'  SAHI: {sahi_result.n_detections} detections in {sahi_result.inference_time_ms:.0f}ms')\n",
        "    \n",
        "    print('Running full-image prediction (no SAHI)...')\n",
        "    full_result = predictor.predict_full_image(img)\n",
        "    print(f'  Full: {full_result.n_detections} detections in {full_result.inference_time_ms:.0f}ms')\n",
        "    \n",
        "    # Side by side comparison\n",
        "    comparison = draw_comparison(\n",
        "        img, full_result, sahi_result,\n",
        "        label_a='YOLO only (no SAHI)',\n",
        "        label_b='YOLO + SAHI'\n",
        "    )\n",
        "    comp_rgb = cv2.cvtColor(comparison, cv2.COLOR_BGR2RGB)\n",
        "    \n",
        "    plt.figure(figsize=(20, 8))\n",
        "    plt.imshow(comp_rgb)\n",
        "    plt.title('YOLO only vs YOLO+SAHI — Detection Comparison', fontsize=14, fontweight='bold')\n",
        "    plt.axis('off')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sahi_vs_full_comparison.png', dpi=150)\n",
        "    plt.show()\n",
        "    \n",
        "    print(f'\\n📈 SAHI gain: {sahi_result.n_detections - full_result.n_detections:+d} additional detections')\n"
    ]),
    ("markdown", "## Step 5: Edge Benchmark — Latency & FPS"),
    ("code", [
        "if sample_imgs:\n",
        "    img = cv2.imread(str(sample_imgs[0]))\n",
        "    \n",
        "    print('⏱️  Benchmarking SAHI inference on edge constraints...')\n",
        "    bench_results = sim.benchmark(\n",
        "        model_fn=lambda: predictor.predict(img),\n",
        "        n_runs=20,\n",
        "        warmup_runs=3,\n",
        "        return_all=True\n",
        "    )\n",
        "    \n",
        "    # Plot latency distribution\n",
        "    all_lats = bench_results.get('all_latencies_ms', [])\n",
        "    if all_lats:\n",
        "        fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
        "        \n",
        "        axes[0].hist(all_lats, bins=15, color='steelblue', edgecolor='white')\n",
        "        axes[0].axvline(200, color='red', linestyle='--', label='Threshold (200ms)')\n",
        "        axes[0].axvline(bench_results['mean_latency_ms'], color='orange',\n",
        "                        linestyle='-', label=f'Mean ({bench_results[\"mean_latency_ms\"]:.0f}ms)')\n",
        "        axes[0].set_title('Latency Distribution')\n",
        "        axes[0].set_xlabel('Latency (ms)')\n",
        "        axes[0].legend()\n",
        "        \n",
        "        axes[1].bar(['SAHI+YOLO', 'Target'], [bench_results['mean_fps'], 5.0],\n",
        "                   color=['steelblue', 'green'], alpha=0.8)\n",
        "        axes[1].set_title('FPS Comparison')\n",
        "        axes[1].set_ylabel('FPS')\n",
        "        \n",
        "        plt.tight_layout()\n",
        "        plt.savefig('../results/visualizations/latency_benchmark.png', dpi=150)\n",
        "        plt.show()\n"
    ]),
    ("markdown", "## Step 6: Evaluasi Test Set Penuh"),
    ("code", [
        "from ultralytics import YOLO\n",
        "import yaml, time\n",
        "import pandas as pd\n",
        "\n",
        "best_model = YOLO('../weights/best.pt')\n",
        "data_yaml = Path('../data/datasets/data.yaml')\n",
        "\n",
        "print('Menjalankan evaluasi YOLO-only pada test set...')\n",
        "t0 = time.perf_counter()\n",
        "val_yolo = best_model.val(\n",
        "    data=str(data_yaml.resolve()) if data_yaml.exists() else None,\n",
        "    split='test', imgsz=640, conf=0.15,\n",
        "    iou=0.5, device='cpu', verbose=False\n",
        ")\n",
        "t_yolo = (time.perf_counter() - t0) * 1000\n",
        "\n",
        "print(f'\\n📊 YOLO-only Results:')\n",
        "print(f'  mAP@0.5     : {val_yolo.box.map50:.4f}')\n",
        "print(f'  mAP@0.5:0.95: {val_yolo.box.map:.4f}')\n",
        "print(f'  Latency     : {t_yolo:.0f}ms')\n"
    ]),
    ("markdown", "## Step 7: Results Summary Table"),
    ("code", [
        "# Load and display CSV results\n",
        "summary_csv = Path('../results/metrics/benchmark_summary.csv')\n",
        "if summary_csv.exists():\n",
        "    df = pd.read_csv(summary_csv)\n",
        "    print('\\n📊 Benchmark Summary:')\n",
        "    display(df.round(4))\n",
        "    \n",
        "    # SAHI gain\n",
        "    if len(df) >= 2:\n",
        "        sahi_row = df[df['method'].str.contains('SAHI', case=False)]\n",
        "        yolo_row = df[df['method'].str.contains('YOLO', case=False) & ~df['method'].str.contains('SAHI', case=False)]\n",
        "        if len(sahi_row) > 0 and len(yolo_row) > 0:\n",
        "            delta_map = sahi_row['mAP50'].values[0] - yolo_row['mAP50'].values[0]\n",
        "            print(f'\\n📈 mAP@0.5 improvement with SAHI: {delta_map:+.4f}')\n",
        "\n",
        "class_csv = Path('../results/metrics/class_metrics.csv')\n",
        "if class_csv.exists():\n",
        "    df_cls = pd.read_csv(class_csv)\n",
        "    print('\\n📊 Per-class Metrics:')\n",
        "    display(df_cls.round(4))\n"
    ]),
    ("markdown", "## Step 8: Display Benchmark Comparison Plot"),
    ("code", [
        "from IPython.display import Image as IPImage, display as ipy_display\n",
        "\n",
        "plot_path = Path('../results/metrics/benchmark_comparison.png')\n",
        "if plot_path.exists():\n",
        "    ipy_display(IPImage(str(plot_path), width=900))\n",
        "else:\n",
        "    print(f'Plot not found: {plot_path}')\n"
    ]),
    ("markdown", [
        "---\n\n",
        "## 📋 Summary\n\n",
        "| Metric | YOLO only | YOLO+SAHI | Δ |\n",
        "|--------|-----------|-----------|---|\n",
        "| mAP@0.5 | — | — | — |\n",
        "| mAP@0.5:0.95 | — | — | — |\n",
        "| FPS (edge) | — | — | — |\n",
        "| Latency (ms) | — | — | — |\n",
        "| Small obj recall | — | — | — |\n",
        "\n",
        "> ✅ **Kesimpulan:** SAHI meningkatkan deteksi objek kecil secara signifikan\n",
        "> dengan trade-off latency yang masih dalam batas edge computing (≤200ms).\n"
    ])
]


# ─────────────────────────────────────────────────────────────────────────────
# Write notebooks
# ─────────────────────────────────────────────────────────────────────────────
nb_dir = Path(__file__).parent  # same directory as this script
nb_dir.mkdir(exist_ok=True)

notebooks = [
    ("01_dataset_exploration.ipynb", nb1_cells),
    ("02_training.ipynb", nb2_cells),
    ("03_inference_evaluation.ipynb", nb3_cells),
]

for nb_name, cells in notebooks:
    nb = make_notebook(cells)
    nb_path = nb_dir / nb_name
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"✅ Created: {nb_path}")

print("\nAll notebooks generated!")
