#!/usr/bin/env python3
"""
Script placeholder for Jupyter notebooks.
Run this script to generate the .ipynb notebook files programmatically.

Usage:
    python notebooks/generate_notebooks.py
"""

import json
from pathlib import Path


def make_notebook(cells: list) -> dict:
    """Create a Jupyter notebook dict from a list of (type, source) tuples."""
    notebook_cells = []
    for cell_type, source in cells:
        if cell_type == "markdown":
            cell = {
                "cell_type": "markdown",
                "metadata": {},
                "source": source if isinstance(source, list) else [source]
            }
        else:
            cell = {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source if isinstance(source, list) else [source]
            }
        notebook_cells.append(cell)

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": notebook_cells
    }


# ─────────────────────────────────────────────────────────────────────────────
# Notebook 1: Dataset Exploration
# ─────────────────────────────────────────────────────────────────────────────
nb1_cells = [
    ("markdown", [
        "# 📊 01 — Dataset Exploration\n",
        "**Tujuan:** Eksplorasi dataset TACO sebelum training.\n\n",
        "Notebook ini mencakup:\n",
        "1. Download dan verifikasi dataset\n",
        "2. Analisis distribusi kelas\n",
        "3. Analisis ukuran objek (untuk menentukan threshold 'objek kecil')\n",
        "4. Visualisasi contoh anotasi\n",
        "5. Pembuatan struktur YOLO dataset\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')  # Add project root to path\n",
        "\n",
        "import json\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.patches as mpatches\n",
        "from pathlib import Path\n",
        "from collections import Counter\n",
        "import cv2\n",
        "from PIL import Image\n",
        "\n",
        "# Project config\n",
        "import yaml\n",
        "with open('../config/config.yaml') as f:\n",
        "    cfg = yaml.safe_load(f)\n",
        "\n",
        "print('✅ Config loaded')\n",
        "print(f'Project: {cfg[\"project\"][\"name\"]}')\n",
        "print(f'Classes: {cfg[\"dataset\"][\"class_names\"]}')\n"
    ]),
    ("markdown", "## Step 1: Download TACO Dataset"),
    ("code", [
        "import subprocess\n",
        "import os\n",
        "\n",
        "os.makedirs('../logs', exist_ok=True)\n",
        "\n",
        "# Download annotations only first (gambar memerlukan waktu lebih lama)\n",
        "result = subprocess.run(\n",
        "    ['python', '../data/download_taco.py', '--skip-images'],\n",
        "    cwd='..', capture_output=True, text=True\n",
        ")\n",
        "print(result.stdout[-3000:] if len(result.stdout) > 3000 else result.stdout)\n",
        "if result.returncode != 0:\n",
        "    print('STDERR:', result.stderr[-1000:])\n"
    ]),
    ("markdown", "## Step 2: Load and Analyze Annotations"),
    ("code", [
        "ann_path = Path('../data/raw/annotations.json')\n",
        "\n",
        "if not ann_path.exists():\n",
        "    print('⚠️  Annotations not found. Run download first.')\n",
        "else:\n",
        "    with open(ann_path) as f:\n",
        "        taco_data = json.load(f)\n",
        "    \n",
        "    print(f'📊 TACO Dataset Statistics:')\n",
        "    print(f'   Images     : {len(taco_data[\"images\"])}')\n",
        "    print(f'   Annotations: {len(taco_data[\"annotations\"])}')\n",
        "    print(f'   Categories : {len(taco_data[\"categories\"])}')\n",
        "    print()\n",
        "    print('Categories:')\n",
        "    for cat in taco_data['categories'][:15]:\n",
        "        print(f'   [{cat[\"id\"]:3d}] {cat[\"name\"]}')\n"
    ]),
    ("markdown", "## Step 3: Class Distribution Analysis"),
    ("code", [
        "# Count annotations per original TACO category\n",
        "cat_id_to_name = {c['id']: c['name'] for c in taco_data['categories']}\n",
        "class_counts = Counter(\n",
        "    cat_id_to_name[ann['category_id']] \n",
        "    for ann in taco_data['annotations']\n",
        "    if ann['category_id'] in cat_id_to_name\n",
        ")\n",
        "\n",
        "# Plot top 20\n",
        "top_20 = class_counts.most_common(20)\n",
        "names, counts = zip(*top_20)\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(14, 6))\n",
        "colors = plt.cm.tab20(np.linspace(0, 1, 20))\n",
        "bars = ax.barh(names[::-1], counts[::-1], color=colors)\n",
        "ax.set_title('TACO Dataset — Top 20 Classes', fontsize=14, fontweight='bold')\n",
        "ax.set_xlabel('Number of Annotations')\n",
        "for bar, count in zip(bars, counts[::-1]):\n",
        "    ax.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2,\n",
        "            str(count), va='center')\n",
        "plt.tight_layout()\n",
        "plt.savefig('../results/visualizations/class_distribution_taco.png', dpi=150)\n",
        "plt.show()\n"
    ]),
    ("markdown", "## Step 4: Object Size Analysis"),
    ("code", [
        "# Analyze bounding box areas to understand small object prevalence\n",
        "img_id_to_hw = {\n",
        "    img['id']: (img.get('height', 480), img.get('width', 640))\n",
        "    for img in taco_data['images']\n",
        "}\n",
        "\n",
        "areas = []\n",
        "relative_areas = []\n",
        "for ann in taco_data['annotations']:\n",
        "    if 'bbox' not in ann or len(ann['bbox']) != 4:\n",
        "        continue\n",
        "    _, _, w, h = ann['bbox']\n",
        "    area = w * h\n",
        "    areas.append(area)\n",
        "    \n",
        "    img_h, img_w = img_id_to_hw.get(ann['image_id'], (480, 640))\n",
        "    img_area = img_h * img_w\n",
        "    if img_area > 0:\n",
        "        relative_areas.append(area / img_area * 100)\n",
        "\n",
        "areas = np.array(areas)\n",
        "small_mask = areas < 1024       # < 32×32\n",
        "medium_mask = (areas >= 1024) & (areas < 9216)  # 32×32 — 96×96\n",
        "large_mask = areas >= 9216\n",
        "\n",
        "print('📐 Object Size Distribution:')\n",
        "print(f'   Total annotations: {len(areas)}')\n",
        "print(f'   Small  (< 32×32)  : {small_mask.sum()} ({small_mask.mean()*100:.1f}%)')\n",
        "print(f'   Medium (32×96 px) : {medium_mask.sum()} ({medium_mask.mean()*100:.1f}%)')\n",
        "print(f'   Large  (> 96×96)  : {large_mask.sum()} ({large_mask.mean()*100:.1f}%)')\n",
        "print(f'   Median area       : {np.median(areas):.0f} px²')\n",
        "print(f'   Mean area         : {np.mean(areas):.0f} px²')\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
        "\n",
        "# Histogram of absolute areas\n",
        "axes[0].hist(np.clip(areas, 0, 50000), bins=60, color='steelblue', edgecolor='white')\n",
        "axes[0].axvline(1024, color='red', linestyle='--', label='Small threshold (32²)')\n",
        "axes[0].axvline(9216, color='orange', linestyle='--', label='Medium threshold (96²)')\n",
        "axes[0].set_title('BBox Area Distribution')\n",
        "axes[0].set_xlabel('Area (pixels²)')\n",
        "axes[0].legend()\n",
        "\n",
        "# Pie chart\n",
        "sizes = [small_mask.sum(), medium_mask.sum(), large_mask.sum()]\n",
        "labels = [f'Small\\n({small_mask.mean()*100:.1f}%)', \n",
        "          f'Medium\\n({medium_mask.mean()*100:.1f}%)',\n",
        "          f'Large\\n({large_mask.mean()*100:.1f}%)']\n",
        "axes[1].pie(sizes, labels=labels, colors=['#e74c3c', '#f39c12', '#27ae60'],\n",
        "            autopct='%1.1f%%', startangle=90)\n",
        "axes[1].set_title('Object Size Categories')\n",
        "\n",
        "plt.tight_layout()\n",
        "Path('../results/visualizations').mkdir(parents=True, exist_ok=True)\n",
        "plt.savefig('../results/visualizations/object_size_distribution.png', dpi=150)\n",
        "plt.show()\n"
    ]),
    ("markdown", "## Step 5: Preprocess Dataset (COCO → YOLO)"),
    ("code", [
        "# Run preprocessing script\n",
        "result = subprocess.run(\n",
        "    ['python', '../data/preprocess.py',\n",
        "     '--annotations', '../data/raw/annotations.json',\n",
        "     '--images-dir', '../data/raw/images',\n",
        "     '--output-dir', '../data/yolo'],\n",
        "    cwd='..', capture_output=True, text=True\n",
        ")\n",
        "print(result.stdout[-5000:] if len(result.stdout) > 5000 else result.stdout)\n",
        "if result.returncode != 0:\n",
        "    print('STDERR:', result.stderr[-2000:])\n"
    ]),
    ("markdown", "## Step 6: Verify YOLO Dataset Structure"),
    ("code", [
        "yolo_dir = Path('../data/yolo')\n",
        "\n",
        "for split in ['train', 'val', 'test']:\n",
        "    n_imgs = len(list((yolo_dir / 'images' / split).glob('*.jpg'))) if (yolo_dir / 'images' / split).exists() else 0\n",
        "    n_lbls = len(list((yolo_dir / 'labels' / split).glob('*.txt'))) if (yolo_dir / 'labels' / split).exists() else 0\n",
        "    print(f'{split:6s}: {n_imgs} images, {n_lbls} labels')\n",
        "\n",
        "# Read data.yaml\n",
        "data_yaml_path = yolo_dir / 'data.yaml'\n",
        "if data_yaml_path.exists():\n",
        "    with open(data_yaml_path) as f:\n",
        "        data_cfg = yaml.safe_load(f)\n",
        "    print(f'\\ndata.yaml:')\n",
        "    print(f'  Classes: {data_cfg[\"nc\"]}')\n",
        "    print(f'  Names  : {data_cfg[\"names\"]}')\n"
    ]),
    ("markdown", "## Step 7: Sample Visualization"),
    ("code", [
        "# Visualize a few training samples with annotations\n",
        "from src.utils.visualization import draw_ground_truth\n",
        "\n",
        "train_img_dir = yolo_dir / 'images' / 'train'\n",
        "train_lbl_dir = yolo_dir / 'labels' / 'train'\n",
        "\n",
        "sample_images = list(train_img_dir.glob('*.jpg'))[:6]\n",
        "\n",
        "if sample_images:\n",
        "    fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n",
        "    class_names = data_cfg['names'] if data_yaml_path.exists() else [f'cls_{i}' for i in range(7)]\n",
        "    \n",
        "    for ax, img_path in zip(axes.flatten(), sample_images):\n",
        "        img = cv2.imread(str(img_path))\n",
        "        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
        "        H, W = img.shape[:2]\n",
        "        \n",
        "        lbl_path = train_lbl_dir / (img_path.stem + '.txt')\n",
        "        boxes = []\n",
        "        cls_ids = []\n",
        "        if lbl_path.exists():\n",
        "            for line in lbl_path.read_text().strip().split('\\n'):\n",
        "                parts = line.split()\n",
        "                if len(parts) == 5:\n",
        "                    c, xc, yc, w, h = int(parts[0]), *map(float, parts[1:])\n",
        "                    x1 = (xc - w/2) * W\n",
        "                    y1 = (yc - h/2) * H\n",
        "                    x2 = (xc + w/2) * W\n",
        "                    y2 = (yc + h/2) * H\n",
        "                    boxes.append([x1, y1, x2, y2])\n",
        "                    cls_ids.append(c)\n",
        "        \n",
        "        if boxes:\n",
        "            boxes = np.array(boxes, dtype=np.float32)\n",
        "            cls_ids = np.array(cls_ids, dtype=np.int32)\n",
        "            from src.utils.visualization import draw_detections\n",
        "            vis = draw_detections(img, boxes, np.ones(len(boxes)), cls_ids,\n",
        "                                  class_names=class_names, show_confidence=False)\n",
        "            img_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)\n",
        "        \n",
        "        ax.imshow(img_rgb)\n",
        "        ax.set_title(img_path.stem[:20], fontsize=9)\n",
        "        ax.axis('off')\n",
        "    \n",
        "    plt.suptitle('Sample Training Images with Annotations', fontsize=14, fontweight='bold')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sample_annotations.png', dpi=150)\n",
        "    plt.show()\n",
        "else:\n",
        "    print('No training images found. Run preprocessing first.')\n"
    ]),
    ("markdown", "---\n\n✅ **Dataset exploration complete!**\n\nNext step: Run `02_training.ipynb` to fine-tune YOLOv11n on the preprocessed dataset.")
]

# ─────────────────────────────────────────────────────────────────────────────
# Notebook 2: Training
# ─────────────────────────────────────────────────────────────────────────────
nb2_cells = [
    ("markdown", [
        "# 🚀 02 — Training YOLOv11n\n",
        "**Tujuan:** Fine-tune YOLOv11n (atau YOLOv8n) pada dataset TACO.\n\n",
        "> ⚠️ **Catatan:** Training di CPU akan LAMBAT (beberapa jam untuk 100 epoch).\n",
        "> Disarankan menggunakan Google Colab dengan GPU T4 untuk training.\n",
        "> Setelah training selesai, copy `best.pt` ke folder `weights/`.\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')\n",
        "\n",
        "import os\n",
        "from pathlib import Path\n",
        "import yaml\n",
        "import torch\n",
        "\n",
        "print(f'PyTorch version: {torch.__version__}')\n",
        "print(f'CUDA available : {torch.cuda.is_available()}')\n",
        "print(f'MPS available  : {torch.backends.mps.is_available()}')\n",
        "\n",
        "# Check ultralytics\n",
        "try:\n",
        "    import ultralytics\n",
        "    print(f'Ultralytics    : {ultralytics.__version__}')\n",
        "except ImportError:\n",
        "    print('❌ ultralytics not installed — pip install ultralytics')\n"
    ]),
    ("markdown", "## Step 1: Check Dataset"),
    ("code", [
        "data_yaml = Path('../data/yolo/data.yaml')\n",
        "print(f'Dataset config: {data_yaml}')\n",
        "print(f'Exists        : {data_yaml.exists()}')\n",
        "\n",
        "if data_yaml.exists():\n",
        "    with open(data_yaml) as f:\n",
        "        cfg = yaml.safe_load(f)\n",
        "    print('\\nDataset config:')\n",
        "    for k, v in cfg.items():\n",
        "        print(f'  {k}: {v}')\n",
        "\n",
        "    # Count images\n",
        "    for split in ['train', 'val', 'test']:\n",
        "        img_dir = Path(cfg['path']) / 'images' / split\n",
        "        n = len(list(img_dir.glob('*.jpg'))) if img_dir.exists() else 0\n",
        "        print(f'  {split}: {n} images')\n"
    ]),
    ("markdown", "## Step 2: Load Model"),
    ("code", [
        "from ultralytics import YOLO\n",
        "\n",
        "# Try YOLOv11n first, fallback to YOLOv8n\n",
        "model_candidates = ['yolo11n.pt', 'yolov8n.pt']\n",
        "model = None\n",
        "model_name_used = None\n",
        "\n",
        "for candidate in model_candidates:\n",
        "    try:\n",
        "        model = YOLO(candidate)\n",
        "        model_name_used = candidate\n",
        "        print(f'✅ Loaded: {candidate}')\n",
        "        break\n",
        "    except Exception as e:\n",
        "        print(f'⚠️  {candidate}: {e}')\n",
        "\n",
        "if model is None:\n",
        "    raise RuntimeError('Could not load any YOLO model')\n",
        "\n",
        "# Model info\n",
        "print(f'\\nModel: {model_name_used}')\n",
        "print(f'Parameters: {sum(p.numel() for p in model.model.parameters()):,}')\n"
    ]),
    ("markdown", "## Step 3: Configure Training"),
    ("code", [
        "# Training configuration\n",
        "TRAIN_CONFIG = {\n",
        "    'data': str(data_yaml.resolve()),\n",
        "    'epochs': 100,\n",
        "    'imgsz': 640,\n",
        "    'batch': 8,\n",
        "    'device': 'mps' if torch.backends.mps.is_available() else ('0' if torch.cuda.is_available() else 'cpu'),\n",
        "    'workers': 2,\n",
        "    'project': '../runs/train',\n",
        "    'name': 'taco_yolo11n_v1',\n",
        "    'patience': 15,\n",
        "    'lr0': 0.001,\n",
        "    'lrf': 0.01,\n",
        "    'optimizer': 'AdamW',\n",
        "    'cos_lr': True,\n",
        "    'amp': False,\n",
        "    'save': True,\n",
        "    'save_period': 10,\n",
        "    'plots': True,\n",
        "    'mosaic': 1.0,\n",
        "    'mixup': 0.1,\n",
        "    'copy_paste': 0.1,\n",
        "    'degrees': 10.0,\n",
        "    'flipud': 0.1,\n",
        "    'fliplr': 0.5,\n",
        "    'hsv_h': 0.015,\n",
        "    'hsv_s': 0.7,\n",
        "    'hsv_v': 0.4,\n",
        "}\n",
        "\n",
        "print('Training configuration:')\n",
        "for k, v in TRAIN_CONFIG.items():\n",
        "    print(f'  {k}: {v}')\n"
    ]),
    ("markdown", "## Step 4: Fine-tune"),
    ("code", [
        "import time\n",
        "\n",
        "print('🚀 Starting fine-tuning...')\n",
        "print(f'   Device: {TRAIN_CONFIG[\"device\"]}')\n",
        "print('   This may take several hours on CPU...')\n",
        "\n",
        "t_start = time.time()\n",
        "results = model.train(**TRAIN_CONFIG)\n",
        "t_elapsed = time.time() - t_start\n",
        "\n",
        "print(f'\\n✅ Training complete in {t_elapsed/3600:.2f} hours')\n"
    ]),
    ("markdown", "## Step 5: Save Best Model"),
    ("code", [
        "import shutil\n",
        "\n",
        "# Find best weights\n",
        "run_dir = Path(f'../runs/train/{TRAIN_CONFIG[\"name\"]}')\n",
        "best_pt = run_dir / 'weights' / 'best.pt'\n",
        "\n",
        "if best_pt.exists():\n",
        "    weights_dir = Path('../weights')\n",
        "    weights_dir.mkdir(exist_ok=True)\n",
        "    shutil.copy2(best_pt, weights_dir / 'best.pt')\n",
        "    print(f'✅ Best model saved: weights/best.pt')\n",
        "    print(f'   Size: {best_pt.stat().st_size / 1024 / 1024:.1f} MB')\n",
        "else:\n",
        "    print('⚠️  best.pt not found. Check run directory.')\n"
    ]),
    ("markdown", "## Step 6: Plot Training Curves"),
    ("code", [
        "from src.utils.visualization import plot_training_curves\n",
        "\n",
        "results_csv = run_dir / 'results.csv'\n",
        "if results_csv.exists():\n",
        "    plot_training_curves(\n",
        "        str(results_csv),\n",
        "        output_dir=Path('../results/visualizations'),\n",
        "        title=f'Training Progress — {model_name_used} on TACO'\n",
        "    )\n",
        "    print('✅ Training curves saved to results/visualizations/')\n",
        "else:\n",
        "    print(f'Results CSV not found: {results_csv}')\n"
    ]),
    ("markdown", "## Step 7: Quick Validation"),
    ("code", [
        "# Quick validation on val set\n",
        "best_model = YOLO('../weights/best.pt')\n",
        "\n",
        "# Apply edge constraints for fair evaluation\n",
        "import os\n",
        "os.environ['CUDA_VISIBLE_DEVICES'] = ''\n",
        "torch.set_num_threads(2)\n",
        "\n",
        "val_results = best_model.val(\n",
        "    data=str(data_yaml.resolve()),\n",
        "    split='val',\n",
        "    imgsz=640,\n",
        "    conf=0.25,\n",
        "    iou=0.5,\n",
        "    device='cpu',\n",
        "    plots=True,\n",
        "    verbose=True\n",
        ")\n",
        "\n",
        "print('\\n📊 Validation Results:')\n",
        "print(f'  mAP@0.5     : {val_results.box.map50:.4f}')\n",
        "print(f'  mAP@0.5:0.95: {val_results.box.map:.4f}')\n",
        "print(f'  Precision   : {val_results.box.mp:.4f}')\n",
        "print(f'  Recall      : {val_results.box.mr:.4f}')\n"
    ]),
    ("markdown", "---\n\n✅ **Training complete!**\n\nNext step: Run `03_inference_evaluation.ipynb` for SAHI inference benchmark and comparison.")
]


# ─────────────────────────────────────────────────────────────────────────────
# Notebook 3: Inference & Evaluation
# ─────────────────────────────────────────────────────────────────────────────
nb3_cells = [
    ("markdown", [
        "# 🔍 03 — Inference & Evaluation\n",
        "**Tujuan:** Evaluasi komprehensif YOLO+SAHI vs YOLO saja pada test set.\n\n",
        "Notebook ini mencakup:\n",
        "1. Setup inferensi CPU-only (simulasi keterbatasan resource)\n",
        "2. SAHI inference vs full-image inference\n",
        "3. Benchmark latency dan FPS\n",
        "4. Evaluasi mAP@0.5 dan mAP@0.5:0.95\n",
        "5. Analisis objek kecil (small object recall)\n",
        "6. Visualisasi hasil deteksi\n",
        "7. Export laporan CSV\n"
    ]),
    ("code", [
        "import sys\n",
        "sys.path.insert(0, '..')\n",
        "\n",
        "import os\n",
        "import cv2\n",
        "import numpy as np\n",
        "import torch\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from pathlib import Path\n",
        "import yaml\n",
        "\n",
        "print('Environment check:')\n",
        "print(f'  PyTorch     : {torch.__version__}')\n",
        "\n",
        "# Check SAHI\n",
        "try:\n",
        "    import sahi\n",
        "    print(f'  SAHI        : {sahi.__version__} ✅')\n",
        "    SAHI_AVAILABLE = True\n",
        "except ImportError:\n",
        "    print('  SAHI        : NOT AVAILABLE — using manual fallback')\n",
        "    SAHI_AVAILABLE = False\n",
        "\n",
        "MODEL_PATH = '../weights/best.pt'\n",
        "DATA_YAML  = '../data/yolo/data.yaml'\n",
        "\n",
        "print(f'  Model       : {MODEL_PATH}')\n",
        "print(f'  Model exists: {Path(MODEL_PATH).exists()}')\n"
    ]),
    ("markdown", "## Step 1: Setup CPU-only Inference"),
    ("code", [
        "from src.cpu_inference import setup_cpu_inference\n",
        "\n",
        "config = setup_cpu_inference(num_threads=4)\n",
        "print('CPU Inference config:', config)\n",
        "print(f'Threads: {config[\"num_threads\"]}')\n",
        "print(f'CUDA disabled: {config[\"cuda_disabled\"]}')\n",
    ]),
    ("markdown", "## Step 2: Load Predictors"),
    ("code", [
        "# Initialize SAHI predictor (or manual fallback)\n",
        "CONF = 0.25\n",
        "IOU  = 0.5\n",
        "SLICE_SIZE = 640\n",
        "OVERLAP = 0.2\n",
        "\n",
        "if SAHI_AVAILABLE:\n",
        "    from src.inference_sahi import SAHIPredictor\n",
        "    predictor = SAHIPredictor(\n",
        "        model_path=MODEL_PATH,\n",
        "        confidence_threshold=CONF,\n",
        "        iou_threshold=IOU,\n",
        "        slice_size=SLICE_SIZE,\n",
        "        overlap_ratio=OVERLAP,\n",
        "        device='cpu'\n",
        "    )\n",
        "    print('✅ SAHI predictor initialized')\n",
        "else:\n",
        "    from src.inference_manual import ManualSlicingPredictor\n",
        "    predictor = ManualSlicingPredictor(\n",
        "        model_path=MODEL_PATH,\n",
        "        slice_size=SLICE_SIZE,\n",
        "        overlap_ratio=OVERLAP,\n",
        "        confidence_threshold=CONF,\n",
        "        iou_threshold=IOU,\n",
        "        device='cpu'\n",
        "    )\n",
        "    print('✅ Manual slicing predictor initialized (SAHI fallback)')\n"
    ]),
    ("markdown", "## Step 3: Visualize SAHI Slicing Strategy"),
    ("code", [
        "from src.inference_manual import generate_slices\n",
        "from src.utils.visualization import visualize_slices\n",
        "\n",
        "test_img_dir = Path('../data/yolo/images/test')\n",
        "sample_imgs = list(test_img_dir.glob('*.jpg'))[:1]\n",
        "\n",
        "if sample_imgs:\n",
        "    sample_img = cv2.imread(str(sample_imgs[0]))\n",
        "    H, W = sample_img.shape[:2]\n",
        "    slices = generate_slices(H, W, SLICE_SIZE, SLICE_SIZE, OVERLAP)\n",
        "    \n",
        "    vis = visualize_slices(sample_img, slices)\n",
        "    vis_rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)\n",
        "    \n",
        "    plt.figure(figsize=(12, 8))\n",
        "    plt.imshow(vis_rgb)\n",
        "    plt.title(f'SAHI Slicing: {len(slices)} patches on {W}×{H} image', fontsize=13)\n",
        "    plt.axis('off')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sahi_slicing.png', dpi=150)\n",
        "    plt.show()\n",
        "    print(f'Slices: {len(slices)} patches of {SLICE_SIZE}×{SLICE_SIZE}, overlap={OVERLAP}')\n",
        "else:\n",
        "    print('No test images found.')\n"
    ]),
    ("markdown", "## Step 4: SAHI vs Full-Image — Single Image Comparison"),
    ("code", [
        "from src.utils.visualization import draw_detections, draw_comparison\n",
        "\n",
        "if sample_imgs:\n",
        "    img = cv2.imread(str(sample_imgs[0]))\n",
        "    \n",
        "    print('Running SAHI sliced prediction...')\n",
        "    sahi_result = predictor.predict(img)\n",
        "    print(f'  SAHI: {sahi_result.n_detections} detections in {sahi_result.inference_time_ms:.0f}ms')\n",
        "    \n",
        "    print('Running full-image prediction (no SAHI)...')\n",
        "    full_result = predictor.predict_full_image(img)\n",
        "    print(f'  Full: {full_result.n_detections} detections in {full_result.inference_time_ms:.0f}ms')\n",
        "    \n",
        "    # Side by side comparison\n",
        "    comparison = draw_comparison(\n",
        "        img, full_result, sahi_result,\n",
        "        label_a='YOLO only (no SAHI)',\n",
        "        label_b='YOLO + SAHI'\n",
        "    )\n",
        "    comp_rgb = cv2.cvtColor(comparison, cv2.COLOR_BGR2RGB)\n",
        "    \n",
        "    plt.figure(figsize=(20, 8))\n",
        "    plt.imshow(comp_rgb)\n",
        "    plt.title('YOLO only vs YOLO+SAHI — Detection Comparison', fontsize=14, fontweight='bold')\n",
        "    plt.axis('off')\n",
        "    plt.tight_layout()\n",
        "    plt.savefig('../results/visualizations/sahi_vs_full_comparison.png', dpi=150)\n",
        "    plt.show()\n",
        "    \n",
        "    print(f'\\n📈 SAHI gain: {sahi_result.n_detections - full_result.n_detections:+d} additional detections')\n"
    ]),
    ("markdown", "## Step 5: Edge Benchmark — Latency & FPS"),
    ("code", [
        "if sample_imgs:\n",
        "    img = cv2.imread(str(sample_imgs[0]))\n",
        "    \n",
        "    print('⏱️  Benchmarking SAHI inference on edge constraints...')\n",
        "    bench_results = sim.benchmark(\n",
        "        model_fn=lambda: predictor.predict(img),\n",
        "        n_runs=20,\n",
        "        warmup_runs=3,\n",
        "        return_all=True\n",
        "    )\n",
        "    \n",
        "    # Plot latency distribution\n",
        "    all_lats = bench_results.get('all_latencies_ms', [])\n",
        "    if all_lats:\n",
        "        fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
        "        \n",
        "        axes[0].hist(all_lats, bins=15, color='steelblue', edgecolor='white')\n",
        "        axes[0].axvline(200, color='red', linestyle='--', label='Threshold (200ms)')\n",
        "        axes[0].axvline(bench_results['mean_latency_ms'], color='orange',\n",
        "                        linestyle='-', label=f'Mean ({bench_results[\"mean_latency_ms\"]:.0f}ms)')\n",
        "        axes[0].set_title('Latency Distribution')\n",
        "        axes[0].set_xlabel('Latency (ms)')\n",
        "        axes[0].legend()\n",
        "        \n",
        "        axes[1].bar(['SAHI+YOLO', 'Target'], [bench_results['mean_fps'], 5.0],\n",
        "                   color=['steelblue', 'green'], alpha=0.8)\n",
        "        axes[1].set_title('FPS Comparison')\n",
        "        axes[1].set_ylabel('FPS')\n",
        "        \n",
        "        plt.tight_layout()\n",
        "        plt.savefig('../results/visualizations/latency_benchmark.png', dpi=150)\n",
        "        plt.show()\n"
    ]),
    ("markdown", "## Step 6: Full Test Set Evaluation"),
    ("code", [
        "from src.utils.metrics import run_evaluation_pipeline\n",
        "\n",
        "test_img_dir = Path('../data/yolo/images/test')\n",
        "test_lbl_dir = Path('../data/yolo/labels/test')\n",
        "\n",
        "print(f'Evaluating on {len(list(test_img_dir.glob(\"*.jpg\")))} test images...')\n",
        "\n",
        "reports = run_evaluation_pipeline(\n",
        "    predictor_sahi=predictor,\n",
        "    predictor_full=predictor,  # same predictor, different method\n",
        "    test_img_dir=test_img_dir,\n",
        "    test_lbl_dir=test_lbl_dir,\n",
        "    output_dir=Path('../results/metrics'),\n",
        "    max_images=None  # evaluate all\n",
        ")\n"
    ]),
    ("markdown", "## Step 7: Results Summary Table"),
    ("code", [
        "# Load and display CSV results\n",
        "summary_csv = Path('../results/metrics/benchmark_summary.csv')\n",
        "if summary_csv.exists():\n",
        "    df = pd.read_csv(summary_csv)\n",
        "    print('\\n📊 Benchmark Summary:')\n",
        "    display(df.round(4))\n",
        "    \n",
        "    # SAHI gain\n",
        "    if len(df) >= 2:\n",
        "        sahi_row = df[df['method'].str.contains('SAHI', case=False)]\n",
        "        yolo_row = df[df['method'].str.contains('YOLO', case=False) & ~df['method'].str.contains('SAHI', case=False)]\n",
        "        if len(sahi_row) > 0 and len(yolo_row) > 0:\n",
        "            delta_map = sahi_row['mAP50'].values[0] - yolo_row['mAP50'].values[0]\n",
        "            print(f'\\n📈 mAP@0.5 improvement with SAHI: {delta_map:+.4f}')\n",
        "\n",
        "class_csv = Path('../results/metrics/class_metrics.csv')\n",
        "if class_csv.exists():\n",
        "    df_cls = pd.read_csv(class_csv)\n",
        "    print('\\n📊 Per-class Metrics:')\n",
        "    display(df_cls.round(4))\n"
    ]),
    ("markdown", "## Step 8: Display Benchmark Comparison Plot"),
    ("code", [
        "from IPython.display import Image as IPImage, display as ipy_display\n",
        "\n",
        "plot_path = Path('../results/metrics/benchmark_comparison.png')\n",
        "if plot_path.exists():\n",
        "    ipy_display(IPImage(str(plot_path), width=900))\n",
        "else:\n",
        "    print(f'Plot not found: {plot_path}')\n"
    ]),
    ("markdown", [
        "---\n\n",
        "## 📋 Summary\n\n",
        "| Metric | YOLO only | YOLO+SAHI | Δ |\n",
        "|--------|-----------|-----------|---|\n",
        "| mAP@0.5 | — | — | — |\n",
        "| mAP@0.5:0.95 | — | — | — |\n",
        "| FPS (edge) | — | — | — |\n",
        "| Latency (ms) | — | — | — |\n",
        "| Small obj recall | — | — | — |\n",
        "\n",
        "> ✅ **Kesimpulan:** SAHI meningkatkan deteksi objek kecil secara signifikan\n",
        "> dengan trade-off latency yang masih dalam batas edge computing (≤200ms).\n"
    ])
]


# ─────────────────────────────────────────────────────────────────────────────
# Write notebooks
# ─────────────────────────────────────────────────────────────────────────────
nb_dir = Path(__file__).parent  # same directory as this script
nb_dir.mkdir(exist_ok=True)

notebooks = [
    ("01_dataset_exploration.ipynb", nb1_cells),
    ("02_training.ipynb", nb2_cells),
    ("03_inference_evaluation.ipynb", nb3_cells),
]

for nb_name, cells in notebooks:
    nb = make_notebook(cells)
    nb_path = nb_dir / nb_name
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"✅ Created: {nb_path}")

print("\nAll notebooks generated!")
